### ISSUE TITLE
Works great, but playback recording would be cool

### ISSUE THREAD

**Issue by thelabcat** [moraell/KinectMocap4Blender#8]
Praise God the plugin works! I'd like to make a feature request, though.
I wanted to use this for animating a character whilst talking, and thus audio syncing is important. I'd like it if the recording process instead of using the built-in-the-addon keying function would instead use the automatic keyframing button, similar to NI-mate addon (IE, start the tracking so the character is Kinect-ed, turn on the automatic keyframing button, and play animation button so it starts recording). I tried doing this as is but for some reason it didn't work, possibly a coding issue such as using one way to set a pose over a different method. I'm new to blender's python API but know a good bit of python, so if you don't have time to do the coding yourself maybe you'd have it easier if you told me how to do it and I do the brunt work, but IDK.

This explains how to use NI mate. But since that software doesn't work for me I'd use the add-on you wrote. The python code in their addon (which network connects to NI-mate) is legible (decently commented and isn't compiled or anything).
https://www.youtube.com/watch?v=1UPZtS5LVvw

Thx again for the great addon and doing this for free!

**Comment by moraell** [comment]
Thanks for the feedback again. I understand what you want. That is actually how I wanted it to work in the first place, but it wasn't possible due to Blender 2.79 issues with multithreading. It may work with Blender 2.80, though, and I can look into it. For now, you can start recording before acting the scene, then remove the beginning, there's a bit of syncing to do but it's not that bad.
I tried NI mate too. It uses non official drivers for Kinect and my computer suffered a lot (I lost my system and some data in the process). I managed to make it work but I wasn't happy with the results, maybe because it was only the trial version. I never achieved the integration with Blender, though. And it is a pretty expensive piece of software. 
I will keep you updated.

**Comment by moraell** [comment]
Here's a modified script for Blender 2.80 that does exactly what you want.
[kinect_mocap.zip](https://github.com/moraell/KinectMocap4Blender/files/3450856/kinect_mocap.zip)
I am not sure I should include it in the project though, because it changes the behaviour between 2.79 and 2.80. But it fits better with how Blender is meant to work (with the auto keying button).

**Comment by thelabcat** [comment]
Awesome, PTL! Thanks!
